# Generated by Django 4.0.2 on 2022-02-23 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imageUrl',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
